### ISSUE TITLE
Error while updating 

### ISSUE THREAD

**Issue by Freez** [sanderdw/hassio-addons#60]
I'm running version 1.1.1 and try to update to the latest's version but it fails. Is it possible to update without reinstalling the package?

`Logger: homeassistant.core
Source: components/hassio/update.py:169
First occurred: 20 juli 2022 om 13:42:02 (2 occurrences)
Last logged: 10:56:22

Error executing service: <ServiceCall update.install (c:01G8DPGHZA9NK48EAESFQJCMAH): entity_id=['update.dsmr_reader_update'], backup=True>
Error executing service: <ServiceCall update.install (c:01G8JHV2JN9KH66PQY47MTFSSG): entity_id=['update.dsmr_reader_update'], backup=True>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: The command '/bin/ash -o pipefail -c curl -J -L -o /tmp/bashio.tar.gz         "https://github.com/hassio-addons/bashio/archive/v0.14.3.tar.gz"     && mkdir /tmp/bashio     && tar zxvf         /tmp/bashio.tar.gz         --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -f -r         /tmp/*' returned a non-zero code: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating DSMR Reader: The command '/bin/ash -o pipefail -c curl -J -L -o /tmp/bashio.tar.gz         "https://github.com/hassio-addons/bashio/archive/v0.14.3.tar.gz"     && mkdir /tmp/bashio     && tar zxvf         /tmp/bashio.tar.gz         --strip 1 -C /tmp/bashio         && mv /tmp/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && rm -f -r         /tmp/*' returned a non-zero code: 1
`

**Comment by sanderdw** [comment]
Yes this is a known issue when upgrading that particular version due to the Home Assistant OS. You can simply remove and install again (make sure to create a backup and remember your settings).
